### ISSUE TITLE
Delete 'Environment' View within a Goal

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#198] opened 2018-03-29 16:25 UTC
### Expected behaviour
Expected one 'Environment' association to be deleted within a Goal. 
I realised out of two external Charlie associated goals, this one "(Charlie)(F2) Acknowledge and input patient information for continuum of care" should not be seen in this Bravo Goal view). So I wanted to delete from the Bravo view. However, CAIRIS may expect you to un-associate the goal's linked Goal or Sub-goals first. Forgetting this, click delete on the Environment and you think it's been deleted, but actually still shows in the Goal list.

After realising it didn't delete as expected, go back in and un-associate the Goal and Sub-goals, and hit delete again. It now looks deleted again from the list, so should not be seen floating in the View still.

### Actual behaviour
The 'Success' alert is displayed. Exit Goal. Then look at model and the asset is still in the environment and also still listed in the Goal list. After going back in to un-associate links and deleting the environment again, it is removed from the list and now you think it is finally deleted, but the Goal can still be seen floating/un-attached in the model view.

### Steps to reproduce the behaviour
This incorrect Goal association should still be in "TMN20180313" file ( or ...141?), so the above steps could potentially be re-created. The goal can be seen floating in later files. 

### Version of CAIRIS
The current version in W/C 12 March 2018

### Operating Systems / Hardware 
Windows 7 with VMware, with Ubuntu17 using Linux Chrome.

**Comment by failys** [comment] 2018-03-29 17:01
Can you please try reproducing this with the ACME Water model?

**Comment by failys** [comment] 2018-03-30 06:58
The root problem seems to be the environment wasn't being removed properly from the goal.   This should be fixed now, but let me know if it isn't.

**Closed** 2018-03-30 06:58 UTC
Labels: bug
