### ISSUE TITLE
Firefox compatibility issues with requirements

### ISSUE THREAD

**Issue by MLaverton** [failys/cairis#140] opened 2017-11-16 10:01 UTC
### Expected behaviour
Drop downs show other options in the priority and type columns on firefox

### Actual behaviour
Priority and type dropdowns do not work

### Steps to reproduce the behaviour
Navigate to Requirements > Requirements on firefox and click a dropdown (In the requirement - priority/type column), the dropdown will not list

### Version of CAIRIS
Latest (demo.cairis.org)

### Operating Systems / Hardware 
Windows 8
Mozilla firefox (Latest version)

**Comment by failys** [comment] 2017-11-16 11:00
Very strange.  I can reproduce this issue on the latest version of Firefox Quantum on Mac OS X (so I presume other versions of Firefox too), but not on any other browser.   The other select elements in CAIRIS seem fine, so I suspect the root cause may be the table widget we're using.  This may take some time to fix, so I would suggest using a different browser in the meantime.  I'll update the documentation to discourage people from using Firefox until we have a fix for this.

**Comment by failys** [comment] 2017-11-16 14:51
Can you please try:
1.  Adding a new requirement, completing the 'Requirement' column, and pressing return so the Success pop up appears.
2.  Repeating for a few other requirements
Are the labels displayed correctly?

It appears to be possible to add, say, 3 requirements, but the only requirement that is added/updated is the row you are working in when you press return.  As the label is generated by the client, you can get out-of-sync requirement labels.

There is an easy workaround for this 'label inconsistency' problem though.  Just export and re-import the model.  During the import process, the labels are then re-generated.

**Comment by failys** [comment] 2017-11-17 12:28
I've just pushed a change to github that fixes this.  Should be available on dec38 and the live demo tomorrow morning.

**Closed by failys** 2017-11-17 12:28 UTC
Labels: bug
